#SPDX-License-Identifier: MIT-0
---
# defaults file for wireguard-server-role

wireguard_conf_owner: nathan
wireguard_conf_group: root
wireguard_conf_mode: "0600"
wireguard_conf_backup: false
wireguard_interface_restart: false
wireguard_update_cache: "true"
wireguard_interface: "wg0"
wireguard_service_enabled: "yes"
wireguard_service_state: "started"
