# SPDX-License-Identifier: MIT-0
---
# defaults file for wireguard-server-role

wireguard_conf_owner: nathan
wireguard_conf_group: root
wireguard_conf_mode: "0600"
wireguard_conf_backup: false
wireguard_interface_restart: false
wireguard_update_cache: "true"
wireguard_interface: "wg0"
wireguard_service_enabled: "true"
wireguard_service_state: "started"
wireguard_remote_directory: "/etc/wireguard"
wireguard_conf_filename: "{{ wireguard_interface }}.conf"
wireguard_is_raspberry_pi: false

wireguard_address: "10.10.10.1/24"
wireguard_port: "51820"
wireguard_saveconfig: "false"

wireguard_postup:
  - ufw route allow in on wg0 out on eth0
  # - iptables -A FORWARD -i wg0 -o wg0 -j ACCEPT
  - iptables -A FORWARD -i %i -j ACCEPT
  - iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
wireguard_predown:
  - ufw route delete allow in on wg0 out on eth0
  # - iptables -D FORWARD -i wg0 -o wg0 -j ACCEPT
  - iptables -D FORWARD -i %i -j ACCEPT
  - iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

wireguard_sysctl_settings:
  # "net.ipv4.tcp_syncookies": 1                     # Enable syn flood protection
  # "net.ipv4.conf.all.accept_source_route": 0       # Ignore source-routed packets
  # "net.ipv6.conf.all.accept_source_route": 0       # IPv6 - Ignore ICMP redirects
  # "net.ipv4.conf.default.accept_source_route": 0   # Ignore source-routed packets
  # "net.ipv6.conf.default.accept_source_route": 0   # IPv6 - Ignore source-routed packets
  # "net.ipv4.conf.all.accept_redirects": 0          # Ignore ICMP redirects
  # "net.ipv6.conf.all.accept_redirects": 0          # IPv6 - Ignore ICMP redirects
  # "net.ipv4.conf.default.accept_redirects": 0      # Ignore ICMP redirects
  # "net.ipv6.conf.default.accept_redirects": 0      # IPv6 - Ignore ICMP redirects
  # "net.ipv4.conf.all.secure_redirects": 1          # Ignore ICMP redirects from non-GW hosts
  # "net.ipv4.conf.default.secure_redirects": 1      # Ignore ICMP redirects from non-GW hosts
  "net.ipv4.ip_forward": 1 # Do allow traffic between networks or act as a router
  # "net.ipv6.conf.all.forwarding": 0                # IPv6 - Do not allow traffic between networks or act as a router
  # "net.ipv4.conf.all.send_redirects": 0            # Don't allow traffic between networks or act as a router
  # "net.ipv4.conf.default.send_redirects": 0        # Don't allow traffic between networks or act as a router
  # "net.ipv4.conf.all.rp_filter": 1                 # Reverse path filtering - IP spoofing protection
  # "net.ipv4.conf.default.rp_filter": 1             # Reverse path filtering - IP spoofing protection
  # "net.ipv4.icmp_echo_ignore_broadcasts": 1        # Ignore ICMP broadcasts to avoid participating in Smurf attacks
  # "net.ipv4.icmp_ignore_bogus_error_responses": 1  # Ignore bad ICMP errors
  # "net.ipv4.icmp_echo_ignore_all": 0               # Ignore bad ICMP errors
  # "net.ipv4.conf.all.log_martians": 1              # Log spoofed, source-routed, and redirect packets
  # "net.ipv4.conf.default.log_martians": 1          # Log spoofed, source-routed, and redirect packets
  # "net.ipv4.tcp_rfc1337": 1                        # Implement RFC 1337 fix
  # "kernel.randomize_va_space": 2                   # Randomize addresses of mmap base, heap, stack and VDSO page
  # "fs.protected_hardlinks": 1                      # Provide protection from ToCToU races
  # "fs.protected_symlinks": 1                       # Provide protection from ToCToU races
  # "kernel.kptr_restrict": 1                        # Make locating kernel addresses more difficult
  # "kernel.perf_event_paranoid": 2                  # Set perf only available to root

wireguard_sshd_settings:
  "^PasswordAuthentication": "PasswordAuthentication no" # Disable password authentication
  # "^PermitRootLogin": "PermitRootLogin no"                # Disable SSH root login
  # "^PermitTunnel": "PermitTunnel no"                      # Disable tun(4) device forwarding
  "^Port ": "Port 22" # Set sshd port

wireguard_ufw_enabled: false

wireguard_ufw_rules:
  - rule: "allow"
    to_port: "51820"
    protocol: "udp"
  - rule: "allow"
    name: "OpenSSH"
