- name: Set Preshared Keys
  block:
    - name: Generate WireGuard Preshared Key
      ansible.builtin.command: "wg genkey"
      register: wireguard__register_preshared_key
      no_log: "{{ ansible_verbosity < 3 }}"
      check_mode: false
      changed_when: true
      tags:
        - wg-generate-keys

    - name: Set preshared key fact
      ansible.builtin.set_fact:
        wireguard_preshared_keys: "{{ wireguard_preshared_keys | default({}) | combine({peer: wireguard__register_preshared_key.stdout}) }}"
      no_log: "{{ ansible_verbosity < 3 }}"
      tags:
        - wg-generate-keys

- name: Set Public and Private Keys
  block:
    - name: Generate WireGuard Preshared Key
      ansible.builtin.command: "wg genkey"
      register: wireguard__register_private_key
      no_log: "{{ ansible_verbosity < 3 }}"
      check_mode: false
      changed_when: true
      tags:
        - wg-generate-keys

    - name: Set private key fact
      ansible.builtin.set_fact:
        wireguard_peer_private_keys: "{{ wireguard_peer_private_keys | default({}) | combine({peer: wireguard__register_private_key.stdout}) }}"
      no_log: "{{ ansible_verbosity < 3 }}"
      tags:
        - wg-generate-keys

    - name: Derive WireGuard public key
      ansible.builtin.command: "wg pubkey"
      args:
        stdin: "{{ wireguard_peer_private_keys[peer] }}"
      register: wireguard__register_public_key
      changed_when: true
      check_mode: false
      no_log: "{{ ansible_verbosity < 3 }}"
      tags:
        - wg-generate-keys

    - name: Set public key fact
      ansible.builtin.set_fact:
        wireguard_peer_public_keys: "{{ wireguard_peer_public_keys | default({}) | combine({peer: wireguard__register_public_key.stdout}) }}"
      tags:
        - wg-generate-keys
