#SPDX-License-Identifier: MIT-0
---
# handlers file for wireguard-server-role

- name: Restart wireguard
  ansible.builtin.service:
    name: "wg-quick@{{ wireguard_interface }}"
    state: "{{ item }}"
  loop:
    - stopped
    - started
  when:
    - wireguard_service_enabled == "yes"
  listen: "reconfigure wireguard"
